package:
  name: numactl-devel-cos7-ppc64le
  version: 2.0.12

source:
  - url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/numactl-devel-2.0.12-3.el7.ppc64le.rpm
    sha256: f4bfb27049880612585278d2f3e3c328d3a627a366567106311299c0524e892d
    folder: binary

build:
  number: 0
  noarch: generic
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - numactl-cos7-ppc64le ==2.0.12
  run:
    - numactl-cos7-ppc64le ==2.0.12

test:
  commands:
    - test -d "${PREFIX}/powerpc64le-conda_cos7-linux-gnu/sysroot"
  requires:
    - zlib

about:
  home: ftp://oss.sgi.com/www/projects/libnuma/download
  license: LGPLv2/GPLv2
  license_family: GPL2
  summary: "(CDT) Development package for building Applications that use numa"
  license_file:
    - copyright.txt
    - gpl-2.0.txt
    - lgpl-2.1.txt
  description: |
        Provides development headers for numa library calls

extra:
  recipe-maintainers:
    - jakirkham
    - ychfan
